### PR TITLE
Anja 1

### PR DESCRIPTION
**Pull request by Boyan-In-Christ**
merge

### CODE REVIEW

**Comment by rogomichael** [comment]
How did you guys merge your code using one file. I am frustrated
Kind regards,

Rogo Michael Opata

**Comment by anjalisa** [comment]
Actually, I haven´t merged anything ;-) I just committed and pushed my changes. Boyan, you merged it?! right?

**Comment by anjalisa** [comment]
AND I had a typo... it is statistical analysis part 1 to 4  (I completed it 2 days ago)

**Comment by rogomichael** [comment]
I think we should meet 10 minutes before the meeting to sort this out!
Kind regards,

Rogo Michael Opata

**Comment by anjalisa** [comment]
where? in her meeting room? I think, this might not work?!

**Comment by Boyan-In-Christ** [comment]
I saw Michael you have reverted your changes right? I merged the changes
from Anja, maybe you can bring your changes back?


rogomichael ***@***.***> 于2021年3月18日周四 上午11:29写道：

> I think we should meet 10 minutes before the meeting to sort this out!
> Kind regards,
>
> Rogo Michael Opata
>
>

**Comment by rogomichael** [comment]
Yes I did because I had made a big mistake. I have issued a pull request
and you can now merge it. I talked to inga about it and she guided me. Lol
Kind regards,

Rogo Michael Opata

**Pull request merged**
